### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by nir0** [oruen/oa-vkontakte#1]
в рельсах3 (ruby 1.9.2) выдает
    /home/rails3/nir0/system/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require': /home/rails3/nir0/system/ruby/1.9.1/bundler/gems/oa-vkontakte-b0ea3996460b/lib/omniauth/strategies/vkontakte_open_api/view_helper.rb:18: invalid multibyte char (US-ASCII) (SyntaxError)
    /home/rails3/nir0/system/ruby/1.9.1/bundler/gems/oa-vkontakte-b0ea3996460b/lib/omniauth/strategies/vkontakte_open_api/view_helper.rb:13: syntax error, unexpected $end, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
первое лечится вставкой в начало файла
    # coding: utf-8
ошибка в ридми
    Добавить в config/initializers/moniauth.rb: 
    Добавить в config/initializers/omniauth.rb: 
Как получить ID приложения? В смысле, куда идти для регистрации сайта?
И можно ли добавить возможность работы без ajax?
Большое спасибо, что выложил это)

**Comment by oruen** [comment]
Спасибо. С 1.9.2 не тестировал ещё.

Создание приложения - здесь - http://vkontakte.ru/developers.php - за кнопкой "Создать приложение". После создания приложения надо зайти в "Редактирование" приложения, перейти на вкладку "Настройки" и там увидеть строку "ID приложения".

Возможность работы без jquery и ajax появится на этой неделе.

**Comment by oruen** [comment]
В 0.1.2 исчезла зависимость от jQuery и вместо ajax-запроса теперь происходит POST на /auth/vkontakte/callback

**Comment by nir0** [comment]
если в lib/omniauth/strategies/vkontakte_open_api/view_helper.rb добавить первой строкой 
    # coding: utf-8
то сервер запустить можно. смотрю дальше...

**Comment by nir0** [comment]
авторизация на серваке запустилась, но на /auth/vkontakte/callback получаем ActionController::InvalidAuthenticityToken

**Comment by nir0** [comment]
ActionController::InvalidAuthenticityToken лечится так:
    lib/omniauth/strategies/vkontakte_open_api/view_helper.rb:66
          }
        }
      }
      input = document.createElement("input");
      input.setAttribute("type", "hidden");
      input.setAttribute("name", "#{request_forgery_protection_token}");
      input.setAttribute("value", "#{form_authenticity_token}");
      form.appendChild(input);
      document.body.appendChild(form);
      form.submit();
      document.body.removeChild(form);

**Comment by oruen** [comment]
authenticity_token в рельсовом хелпере и кодировка во ViewHelper. Closed by 4535c423fb6828ad645322b92546f64660e09e74.
