### ISSUE TITLE
OAuth ВКонтакте

### ISSUE THREAD

**Issue by sandrew** [oruen/oa-vkontakte#2]
Вконтакт на днях наконец реализовал OAuth 2.0
Мне кажется, что пришло время переделать авторизацию с JS API на OAuth, сделать pull request на omniauth и закрыть проект. Вы сможете это сделать?
Здесь, если что, описано подробнее: http://habrahabr.ru/blogs/social_networks/117211/

**Comment by oruen** [comment]
Да, займусь этим, спасибо за наводку.

**Comment by mprokopov** [comment]
поддерживаю предыдущего оратора

**Comment by sandrew** [comment]
https://gist.github.com/936275
я сделал strategy для OmniAuth, но её было бы неплохо потестить, да залить в основное репо. Сейчас нет на это времени.

**Comment by german** [comment]
стратегия для контакта есть уже с 0.2.3 https://github.com/intridea/omniauth/pull/272 например

**Comment by oruen** [comment]
Отличная новость! Спасибо, Дмитрий.
