### ISSUE TITLE
OmniAuth 1.0

### ISSUE THREAD

**Issue by mamantoha** [oruen/oa-vkontakte#4]
Начиная с OmniAuth 1.0, каждый  стратегия будет жить в своем собственном gem’е? Вы собираетесь адаптировать стратегию Vkontakte для OmniAuth 1.0 ?

https://github.com/intridea/omniauth/wiki/List-of-Strategies
https://github.com/intridea/omniauth/wiki/Strategy-Contribution-Guide

**Comment by oruen** [comment]
Не собирался. Этот гем является устаревшим с момента включения модуля для работы с Вконтакте в основной репозиторий проекта omniauth.

**Comment by mamantoha** [comment]
Спасибо за ответ. Код с 0.3.2 уже адаптирован для 1.0.
